[build-system]
# this should match SETUP_REQUIRES in setup.py, with the addition of setuptools
# and wheel (in case some point in the future pip does not assume setuptools and
# wheel)
requires = [
  "setuptools",
  "wheel",
  "numpy==1.12.0; python_version=='3.6'",
  "numpy==1.14.3; python_version>='3.7'",
  "Cython>=0.23",
  "pkgconfig"
]
